# Generated by Django 4.1.7 on 2023-03-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='articles',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='fileinput',
            name='articles',
            field=models.FileField(blank=True, null=True, upload_to='xlsx/', verbose_name='Выберете файл для загрузки'),
        ),
    ]
